version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godot
    - ireturn
    - mnd
    - nlreturn
    - nolintlint
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
  settings:
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: pa/private.go
      - linters:
          - gocritic
          - staticcheck
        path: pa/pa_test.go
      - linters:
          - funlen
          - lll
        path: internal/q/q_test.go
      - linters:
          - mnd
        path: internal/q/cmd/main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
