version: "2"
run:
  tests: true
issues:
  max-same-issues: 0
linters:
  default: all
  enable:
    - gomodguard_v2
    - nolintlint
  disable:
    - exhaustruct
    - exhaustruct_v5
    - forbidigo # we need to use fmt.Print*()
    - funlen
    - gochecknoglobals # why the fuck i am not allowed to use globals
    - gocognit
    - gocyclo
    - godot
    - godox # TODO: remove
    - gomodguard
    - gosmopolitan
    - ireturn # i know better
    - mnd
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - testpackage
    - varnamelen # makes bad suggestions
    - wsl
    - wsl_v5
    # TODO: remove
    - cyclop
    - depguard
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - exhaustive
    - forcetypeassert
    - gocritic
    - godoclint
    - gosec
    - govet
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - maintidx
    - modernize
    - nestif
    - noctx
    - paralleltest
    - recvcheck
    - revive
    - staticcheck
    - tparallel
    - unused
    - wrapcheck
  settings:
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 10
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      ignore-tests: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: power_assert_private.go
      - linters:
          - gocritic
          - staticcheck
        path: power_assert_test.go
      - linters:
          - funlen
          - lll
        path: internal/q/q_test.go
      - linters:
          - mnd
        path: internal/q/cmd/main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofumpt:
      extra:
        group-params: true
        clothe-returns: true
        balance-calls: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
